"""Add World Wiki models

Revision ID: 017c14e9d06a
Revises: 872d71386ef2
Create Date: 2026-02-04 01:58:40.781953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '017c14e9d06a'
down_revision: Union[str, Sequence[str], None] = '872d71386ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('progress_type', sa.String(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_progress_user_id'), 'achievement_progress', ['user_id'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_type', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('brainstorm_ideas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('idea_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('idea_metadata', sa.JSON(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('integrated_to_outline', sa.Boolean(), nullable=True),
    sa.Column('integrated_to_codex', sa.Boolean(), nullable=True),
    sa.Column('plot_beat_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('ai_cost', sa.Float(), nullable=True),
    sa.Column('ai_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['plot_beat_id'], ['plot_beats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['brainstorm_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_beats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outline_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('parent_beat_id', sa.String(), nullable=True),
    sa.Column('beat_name', sa.String(), nullable=False),
    sa.Column('beat_label', sa.String(), nullable=False),
    sa.Column('beat_description', sa.Text(), nullable=True),
    sa.Column('target_position_percent', sa.Float(), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=True),
    sa.Column('actual_word_count', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('brainstorm_source_id', sa.String(), nullable=True),
    sa.Column('linked_manuscript_outline_id', sa.String(), nullable=True),
    sa.Column('target_book_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_source_id'], ['brainstorm_ideas.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['linked_manuscript_outline_id'], ['outlines.id'], ),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
    sa.ForeignKeyConstraint(['parent_beat_id'], ['plot_beats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shareable_recaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('share_id', sa.String(length=6), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('recap_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_content_type', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('recap_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareable_recaps_share_id'), 'shareable_recaps', ['share_id'], unique=True)
    op.create_table('travel_speed_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('speeds', sa.JSON(), nullable=False),
    sa.Column('default_speed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_speed_profiles_manuscript_id'), 'travel_speed_profiles', ['manuscript_id'], unique=True)
    op.create_table('worlds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_learning',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('pattern_key', sa.String(), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['writing_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_learning_user_id'), 'author_learning', ['user_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_privacy_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('allow_training_data', sa.Boolean(), nullable=False),
    sa.Column('allow_ai_assistance', sa.Boolean(), nullable=False),
    sa.Column('ai_context_retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manuscript_id')
    )
    op.create_table('carbon_budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('budget_period', sa.String(), nullable=True),
    sa.Column('budget_micro_gco2', sa.Integer(), nullable=True),
    sa.Column('current_usage_micro_gco2', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('warn_threshold', sa.Integer(), nullable=True),
    sa.Column('limit_threshold', sa.Integer(), nullable=True),
    sa.Column('limit_action', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('operation_subtype', sa.String(), nullable=True),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('energy_micro_kwh', sa.Integer(), nullable=True),
    sa.Column('carbon_intensity', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('emissions_micro_gco2', sa.Integer(), nullable=True),
    sa.Column('tokens_processed', sa.Integer(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=True),
    sa.Column('compute_ms', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('cache_hit', sa.Integer(), nullable=True),
    sa.Column('batched', sa.Integer(), nullable=True),
    sa.Column('deferred', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('total_energy_micro_kwh', sa.Integer(), nullable=True),
    sa.Column('total_emissions_micro_gco2', sa.Integer(), nullable=True),
    sa.Column('emissions_breakdown', sa.JSON(), nullable=True),
    sa.Column('sci_score', sa.Float(), nullable=True),
    sa.Column('functional_unit', sa.String(), nullable=True),
    sa.Column('functional_unit_count', sa.Integer(), nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('requests_batched', sa.Integer(), nullable=True),
    sa.Column('requests_deferred', sa.Integer(), nullable=True),
    sa.Column('estimated_savings_micro_gco2', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('previous_period_emissions', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('initial_context', sa.JSON(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_sessions_user_id'), 'coach_sessions', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('consent_type', sa.String(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('world_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('structure_type', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('arc_type', sa.String(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('target_word_count', sa.Integer(), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('logline', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brainstorm_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('outline_id', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_distances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('location_a_id', sa.String(), nullable=False),
    sa.Column('location_b_id', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('distance_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_distances_manuscript_id'), 'location_distances', ['manuscript_id'], unique=False)
    op.create_table('wiki_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_seed', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('linked_entity_id', sa.String(), nullable=True),
    sa.Column('source_manuscripts', sa.JSON(), nullable=True),
    sa.Column('source_chapters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['wiki_entries.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('agent_types', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('teaching_points', sa.JSON(), nullable=True),
    sa.Column('agent_results', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_analyses_manuscript_id'), 'agent_analyses', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_agent_analyses_user_id'), 'agent_analyses', ['user_id'], unique=False)
    op.create_table('ai_interaction_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tokens_sent', sa.Integer(), nullable=True),
    sa.Column('tokens_received', sa.Integer(), nullable=True),
    sa.Column('training_opted_out', sa.Boolean(), nullable=False),
    sa.Column('zero_data_retention', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('estimated_cost_usd', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=False),
    sa.Column('end_position', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_arcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wiki_entry_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('arc_template', sa.String(), nullable=True),
    sa.Column('arc_name', sa.String(), nullable=True),
    sa.Column('planned_arc', sa.JSON(), nullable=True),
    sa.Column('detected_arc', sa.JSON(), nullable=True),
    sa.Column('arc_beats', sa.JSON(), nullable=True),
    sa.Column('custom_stages', sa.JSON(), nullable=True),
    sa.Column('arc_completion', sa.Float(), nullable=True),
    sa.Column('arc_health', sa.String(), nullable=True),
    sa.Column('arc_deviation_notes', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['wiki_entry_id'], ['wiki_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_source_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('character_offset', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('recap_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wiki_entry_id', sa.String(), nullable=True),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('proposed_entry', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_chapter_id', sa.String(), nullable=True),
    sa.Column('source_manuscript_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['source_manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['wiki_entry_id'], ['wiki_entries.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki_cross_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_entry_id', sa.String(), nullable=False),
    sa.Column('target_entry_id', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('context_chapter_id', sa.String(), nullable=True),
    sa.Column('bidirectional', sa.Integer(), nullable=True),
    sa.Column('display_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['context_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['source_entry_id'], ['wiki_entries.id'], ),
    sa.ForeignKeyConstraint(['target_entry_id'], ['wiki_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wiki_entry_id', sa.String(), nullable=True),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('validation_keywords', sa.JSON(), nullable=True),
    sa.Column('validation_pattern', sa.Text(), nullable=True),
    sa.Column('exception_keywords', sa.JSON(), nullable=True),
    sa.Column('exception_pattern', sa.Text(), nullable=True),
    sa.Column('valid_examples', sa.JSON(), nullable=True),
    sa.Column('violation_examples', sa.JSON(), nullable=True),
    sa.Column('violation_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('check_scope', sa.JSON(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wiki_entry_id'], ['wiki_entries.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_appearances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('chapter_scene_id', sa.String(), nullable=True),
    sa.Column('timeline_event_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('ai_generated', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('appearance_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_scene_id'], ['chapter_scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_timeline_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('timeline_event_id', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('narrative_timestamp', sa.String(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_canonical', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_timeline_states_entity_id'), 'entity_timeline_states', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_timeline_states_manuscript_id'), 'entity_timeline_states', ['manuscript_id'], unique=False)
    op.create_table('foreshadowing_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('foreshadowing_event_id', sa.String(), nullable=False),
    sa.Column('foreshadowing_type', sa.String(), nullable=False),
    sa.Column('foreshadowing_text', sa.Text(), nullable=False),
    sa.Column('payoff_event_id', sa.String(), nullable=True),
    sa.Column('payoff_text', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_event_id'], ['timeline_events.id'], ),
    sa.ForeignKeyConstraint(['payoff_event_id'], ['timeline_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadowing_pairs_manuscript_id'), 'foreshadowing_pairs', ['manuscript_id'], unique=False)
    op.create_table('rule_violations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=True),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('character_offset', sa.Integer(), nullable=True),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['world_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('suggestion_type', sa.String(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('manuscript_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('modified_text', sa.Text(), nullable=True),
    sa.Column('user_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['agent_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_feedback_user_id'), 'suggestion_feedback', ['user_id'], unique=False)
    op.create_table('travel_legs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manuscript_id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('from_location_id', sa.String(), nullable=False),
    sa.Column('to_location_id', sa.String(), nullable=False),
    sa.Column('departure_event_id', sa.String(), nullable=False),
    sa.Column('arrival_event_id', sa.String(), nullable=False),
    sa.Column('travel_mode', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('speed_kmh', sa.Integer(), nullable=True),
    sa.Column('required_hours', sa.Integer(), nullable=True),
    sa.Column('available_hours', sa.Integer(), nullable=True),
    sa.Column('is_feasible', sa.Integer(), nullable=True),
    sa.Column('leg_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_event_id'], ['timeline_events.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['departure_event_id'], ['timeline_events.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_legs_manuscript_id'), 'travel_legs', ['manuscript_id'], unique=False)
    op.drop_table('voice_comparisons')
    op.drop_index(op.f('ix_voice_inconsistencies_character'), table_name='voice_inconsistencies')
    op.drop_index(op.f('ix_voice_inconsistencies_manuscript'), table_name='voice_inconsistencies')
    op.drop_table('voice_inconsistencies')
    op.drop_index(op.f('ix_voice_profiles_manuscript_character'), table_name='character_voice_profiles')
    op.drop_table('character_voice_profiles')
    # SQLite: Add columns without foreign key constraints (SQLite doesn't support ALTER for FK)
    op.add_column('chapters', sa.Column('document_type', sa.String(), nullable=True, server_default='chapter'))
    op.add_column('chapters', sa.Column('linked_entity_id', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('document_metadata', sa.JSON(), nullable=True))
    # op.create_foreign_key(None, 'chapters', 'entities', ['linked_entity_id'], ['id'])  # Skip for SQLite
    op.add_column('entities', sa.Column('world_id', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('scope', sa.String(), nullable=True, server_default='MANUSCRIPT'))
    op.add_column('entities', sa.Column('template_type', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('template_data', sa.JSON(), nullable=True))
    # op.alter_column('entities', 'manuscript_id', existing_type=sa.VARCHAR(), nullable=True)  # Skip for SQLite
    # op.create_foreign_key(None, 'entities', 'worlds', ['world_id'], ['id'])  # Skip for SQLite
    op.add_column('entity_suggestions', sa.Column('extracted_description', sa.Text(), nullable=True))
    op.add_column('entity_suggestions', sa.Column('extracted_attributes', sa.JSON(), nullable=True))
    op.add_column('manuscripts', sa.Column('premise', sa.Text(), nullable=True))
    op.add_column('manuscripts', sa.Column('premise_source', sa.String(), nullable=True))
    op.add_column('manuscripts', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('manuscripts', sa.Column('series_id', sa.String(), nullable=True))
    op.add_column('manuscripts', sa.Column('order_index', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'manuscripts', 'series', ['series_id'], ['id'])  # Skip for SQLite
    op.add_column('scenes', sa.Column('pov_character_id', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'scenes', 'entities', ['pov_character_id'], ['id'])  # Skip for SQLite
    # op.create_foreign_key(None, 'scenes', 'chapters', ['chapter_id'], ['id'])  # Skip for SQLite
    op.add_column('snapshots', sa.Column('auto_summary', sa.Text(), nullable=True))
    op.add_column('timeline_events', sa.Column('source_chapter_id', sa.String(), nullable=True))
    op.add_column('timeline_events', sa.Column('source_text_offset', sa.Integer(), nullable=True))
    op.add_column('timeline_events', sa.Column('narrative_importance', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('timeline_events', sa.Column('prerequisite_ids', sa.JSON(), nullable=True, server_default='[]'))
    # op.create_foreign_key(None, 'timeline_events', 'chapters', ['source_chapter_id'], ['id'])  # Skip for SQLite
    op.add_column('timeline_inconsistencies', sa.Column('suggestion', sa.Text(), nullable=True))
    op.add_column('timeline_inconsistencies', sa.Column('teaching_point', sa.Text(), nullable=True))
    op.add_column('timeline_inconsistencies', sa.Column('is_resolved', sa.Integer(), nullable=True))
    op.add_column('timeline_inconsistencies', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('timeline_inconsistencies', sa.Column('resolution_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_inconsistencies', 'resolution_notes')
    op.drop_column('timeline_inconsistencies', 'resolved_at')
    op.drop_column('timeline_inconsistencies', 'is_resolved')
    op.drop_column('timeline_inconsistencies', 'teaching_point')
    op.drop_column('timeline_inconsistencies', 'suggestion')
    # op.drop_constraint(None, 'timeline_events', type_='foreignkey')  # Skip for SQLite
    op.drop_column('timeline_events', 'prerequisite_ids')
    op.drop_column('timeline_events', 'narrative_importance')
    op.drop_column('timeline_events', 'source_text_offset')
    op.drop_column('timeline_events', 'source_chapter_id')
    op.drop_column('snapshots', 'auto_summary')
    # op.drop_constraint(None, 'scenes', type_='foreignkey')  # Skip for SQLite
    # op.drop_constraint(None, 'scenes', type_='foreignkey')  # Skip for SQLite
    op.drop_column('scenes', 'pov_character_id')
    # op.drop_constraint(None, 'manuscripts', type_='foreignkey')  # Skip for SQLite
    op.drop_column('manuscripts', 'order_index')
    op.drop_column('manuscripts', 'series_id')
    op.drop_column('manuscripts', 'genre')
    op.drop_column('manuscripts', 'premise_source')
    op.drop_column('manuscripts', 'premise')
    op.drop_column('entity_suggestions', 'extracted_attributes')
    op.drop_column('entity_suggestions', 'extracted_description')
    # op.drop_constraint(None, 'entities', type_='foreignkey')  # Skip for SQLite
    # op.alter_column('entities', 'manuscript_id', existing_type=sa.VARCHAR(), nullable=False)  # Skip for SQLite
    op.drop_column('entities', 'template_data')
    op.drop_column('entities', 'template_type')
    op.drop_column('entities', 'scope')
    op.drop_column('entities', 'world_id')
    # op.drop_constraint(None, 'chapters', type_='foreignkey')  # Skip for SQLite
    op.drop_column('chapters', 'document_metadata')
    op.drop_column('chapters', 'linked_entity_id')
    op.drop_column('chapters', 'document_type')
    op.create_table('character_voice_profiles',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('character_id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('profile_data', sqlite.JSON(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_manuscript_character'), 'character_voice_profiles', ['manuscript_id', 'character_id'], unique=False)
    op.create_table('voice_inconsistencies',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_id', sa.VARCHAR(), nullable=False),
    sa.Column('chapter_id', sa.VARCHAR(), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('inconsistency_type', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('dialogue_excerpt', sa.TEXT(), nullable=True),
    sa.Column('start_offset', sa.INTEGER(), nullable=True),
    sa.Column('end_offset', sa.INTEGER(), nullable=True),
    sa.Column('expected_value', sa.VARCHAR(), nullable=True),
    sa.Column('actual_value', sa.VARCHAR(), nullable=True),
    sa.Column('suggestion', sa.TEXT(), nullable=True),
    sa.Column('teaching_point', sa.TEXT(), nullable=True),
    sa.Column('is_resolved', sa.INTEGER(), nullable=True),
    sa.Column('user_feedback', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['character_voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_inconsistencies_manuscript'), 'voice_inconsistencies', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_voice_inconsistencies_character'), 'voice_inconsistencies', ['character_id'], unique=False)
    op.create_table('voice_comparisons',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_a_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_b_id', sa.VARCHAR(), nullable=False),
    sa.Column('overall_similarity', sa.FLOAT(), nullable=True),
    sa.Column('vocabulary_similarity', sa.FLOAT(), nullable=True),
    sa.Column('structure_similarity', sa.FLOAT(), nullable=True),
    sa.Column('formality_similarity', sa.FLOAT(), nullable=True),
    sa.Column('comparison_data', sqlite.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['character_a_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_travel_legs_manuscript_id'), table_name='travel_legs')
    op.drop_table('travel_legs')
    op.drop_index(op.f('ix_suggestion_feedback_user_id'), table_name='suggestion_feedback')
    op.drop_table('suggestion_feedback')
    op.drop_table('rule_violations')
    op.drop_index(op.f('ix_foreshadowing_pairs_manuscript_id'), table_name='foreshadowing_pairs')
    op.drop_table('foreshadowing_pairs')
    op.drop_index(op.f('ix_entity_timeline_states_manuscript_id'), table_name='entity_timeline_states')
    op.drop_index(op.f('ix_entity_timeline_states_entity_id'), table_name='entity_timeline_states')
    op.drop_table('entity_timeline_states')
    op.drop_table('entity_appearances')
    op.drop_table('world_rules')
    op.drop_table('wiki_cross_references')
    op.drop_table('wiki_changes')
    op.drop_table('recaps')
    op.drop_table('entity_source_references')
    op.drop_table('character_arcs')
    op.drop_table('chapter_scenes')
    op.drop_table('ai_interaction_audit')
    op.drop_index(op.f('ix_agent_analyses_user_id'), table_name='agent_analyses')
    op.drop_index(op.f('ix_agent_analyses_manuscript_id'), table_name='agent_analyses')
    op.drop_table('agent_analyses')
    op.drop_table('wiki_entries')
    op.drop_index(op.f('ix_location_distances_manuscript_id'), table_name='location_distances')
    op.drop_table('location_distances')
    op.drop_table('coach_messages')
    op.drop_table('brainstorm_sessions')
    op.drop_table('outlines')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_coach_sessions_user_id'), table_name='coach_sessions')
    op.drop_table('coach_sessions')
    op.drop_table('carbon_reports')
    op.drop_table('carbon_metrics')
    op.drop_table('carbon_budgets')
    op.drop_table('author_privacy_preferences')
    op.drop_table('series')
    op.drop_index(op.f('ix_author_learning_user_id'), table_name='author_learning')
    op.drop_table('author_learning')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_travel_speed_profiles_manuscript_id'), table_name='travel_speed_profiles')
    op.drop_table('travel_speed_profiles')
    op.drop_index(op.f('ix_shareable_recaps_share_id'), table_name='shareable_recaps')
    op.drop_table('shareable_recaps')
    op.drop_table('plot_beats')
    op.drop_table('brainstorm_ideas')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_achievement_progress_user_id'), table_name='achievement_progress')
    op.drop_table('achievement_progress')
    # ### end Alembic commands ###
