"""Add outline and plot_beats tables for story structure

Revision ID: 4e6fb3446c33
Revises: 6ee849b26379
Create Date: 2026-01-03 23:46:02.561320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4e6fb3446c33'
down_revision: Union[str, Sequence[str], None] = '6ee849b26379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old timeline tables (cleanup)
    try:
        op.drop_index(op.f('ix_timeline_events_manuscript_id'), table_name='timeline_events')
        op.drop_table('timeline_events')
    except:
        pass
    try:
        op.drop_index(op.f('ix_character_locations_manuscript_id'), table_name='character_locations')
        op.drop_table('character_locations')
    except:
        pass
    try:
        op.drop_index(op.f('ix_timeline_inconsistencies_manuscript_id'), table_name='timeline_inconsistencies')
        op.drop_table('timeline_inconsistencies')
    except:
        pass

    # Create outlines table
    op.create_table(
        'outlines',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('manuscript_id', sa.String(), nullable=False),
        sa.Column('structure_type', sa.String(), nullable=False),
        sa.Column('genre', sa.String(), nullable=True),
        sa.Column('target_word_count', sa.Integer(), nullable=True),
        sa.Column('premise', sa.Text(), nullable=True),
        sa.Column('logline', sa.Text(), nullable=True),
        sa.Column('synopsis', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('settings', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create plot_beats table
    op.create_table(
        'plot_beats',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('outline_id', sa.String(), nullable=False),
        sa.Column('beat_name', sa.String(), nullable=False),
        sa.Column('beat_label', sa.String(), nullable=False),
        sa.Column('beat_description', sa.Text(), nullable=True),
        sa.Column('target_position_percent', sa.Float(), nullable=False),
        sa.Column('target_word_count', sa.Integer(), nullable=True),
        sa.Column('actual_word_count', sa.Integer(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('user_notes', sa.Text(), nullable=True),
        sa.Column('content_summary', sa.Text(), nullable=True),
        sa.Column('chapter_id', sa.String(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop outline tables
    op.drop_table('plot_beats')
    op.drop_table('outlines')

    # Restore old timeline tables
    op.create_table('timeline_inconsistencies',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('inconsistency_type', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.Column('affected_event_ids', sqlite.JSON(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_inconsistencies_manuscript_id'), 'timeline_inconsistencies', ['manuscript_id'], unique=False)
    op.create_table('character_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_id', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_locations_manuscript_id'), 'character_locations', ['manuscript_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('character_ids', sqlite.JSON(), nullable=False),
    sa.Column('event_metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_manuscript_id'), 'timeline_events', ['manuscript_id'], unique=False)
    # ### end Alembic commands ###
