"""Add brainstorming tables

Revision ID: 927396b0fa40
Revises: 4e6fb3446c33
Create Date: 2026-01-05 14:25:16.611011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '927396b0fa40'
down_revision: Union[str, Sequence[str], None] = '4e6fb3446c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_locations_manuscript_id'), table_name='character_locations')
    op.drop_table('character_locations')
    op.drop_index(op.f('ix_timeline_inconsistencies_manuscript_id'), table_name='timeline_inconsistencies')
    op.drop_table('timeline_inconsistencies')
    op.drop_index(op.f('ix_timeline_events_manuscript_id'), table_name='timeline_events')
    op.drop_table('timeline_events')

    # Create brainstorm_sessions table
    op.create_table('brainstorm_sessions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('manuscript_id', sa.String(), nullable=False),
        sa.Column('outline_id', sa.String(), nullable=True),
        sa.Column('session_type', sa.String(), nullable=False),
        sa.Column('context_data', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
        sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create brainstorm_ideas table
    op.create_table('brainstorm_ideas',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('idea_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('idea_metadata', sa.JSON(), nullable=True),
        sa.Column('is_selected', sa.Boolean(), nullable=True),
        sa.Column('user_notes', sa.Text(), nullable=True),
        sa.Column('edited_content', sa.Text(), nullable=True),
        sa.Column('integrated_to_outline', sa.Boolean(), nullable=True),
        sa.Column('integrated_to_codex', sa.Boolean(), nullable=True),
        sa.Column('plot_beat_id', sa.String(), nullable=True),
        sa.Column('entity_id', sa.String(), nullable=True),
        sa.Column('ai_cost', sa.Float(), nullable=True),
        sa.Column('ai_tokens', sa.Integer(), nullable=True),
        sa.Column('ai_model', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['brainstorm_sessions.id'], ),
        sa.ForeignKeyConstraint(['plot_beat_id'], ['plot_beats.id'], ),
        sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add brainstorm_source_id column to plot_beats (without foreign key due to SQLite limitations)
    op.add_column('plot_beats', sa.Column('brainstorm_source_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop brainstorm_source_id column from plot_beats
    op.drop_column('plot_beats', 'brainstorm_source_id')

    # Drop brainstorm tables
    op.drop_table('brainstorm_ideas')
    op.drop_table('brainstorm_sessions')
    op.create_table('timeline_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('location_id', sa.VARCHAR(), nullable=True),
    sa.Column('character_ids', sqlite.JSON(), nullable=False),
    sa.Column('event_metadata', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_manuscript_id'), 'timeline_events', ['manuscript_id'], unique=False)
    op.create_table('timeline_inconsistencies',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('inconsistency_type', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.Column('affected_event_ids', sqlite.JSON(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_inconsistencies_manuscript_id'), 'timeline_inconsistencies', ['manuscript_id'], unique=False)
    op.create_table('character_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('manuscript_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_id', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('location_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['timeline_events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_locations_manuscript_id'), 'character_locations', ['manuscript_id'], unique=False)
    # ### end Alembic commands ###
